# Generated by Django 3.0.6 on 2020-05-06 18:36

import accounts.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=60)),
                ('autore', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('1', 'Tema scolastico'), ('2', 'Saggio'), ('3', 'Articolo di giornale'), ('4', 'Altro')], default='1', max_length=30)),
                ('descrizione', models.CharField(blank=True, max_length=300)),
                ('term_unici', models.IntegerField(default=0)),
                ('term_totali', models.IntegerField(default=0)),
                ('complessita', models.FloatField(default=0)),
                ('pubblicatore', models.ForeignKey(default=accounts.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Testi',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parola', models.CharField(max_length=30)),
                ('frequenza', models.IntegerField(default=0)),
                ('testo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Testo')),
            ],
            options={
                'unique_together': {('testo', 'parola')},
            },
        ),
    ]
