# Generated by Django 3.0.6 on 2020-05-18 08:38

import accounts.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0002_auto_20200506_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParolaBlacklist',
            fields=[
                ('parola', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parola', models.ManyToManyField(to='catalogo.ParolaBlacklist')),
                ('utente', models.OneToOneField(default=accounts.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
