# Generated by Django 3.0.6 on 2020-05-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_blacklist_parolablacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='parola',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='parola',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='catalogo.ParolaBlacklist'),
        ),
    ]
