# Generated by Django 3.0.6 on 2020-05-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20200518_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.DeleteModel(
            name='ParolaBlacklist',
        ),
    ]
