# Generated by Django 3.0.6 on 2020-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20200518_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testo',
            name='autore',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
