# Generated by Django 3.0.6 on 2020-05-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20200521_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testo',
            name='autore',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testo',
            name='titolo',
            field=models.CharField(max_length=255),
        ),
    ]
