# Generated by Django 3.0.6 on 2020-05-18 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='parola',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together={('utente', 'parola')},
        ),
        migrations.DeleteModel(
            name='ParolaBlacklist',
        ),
    ]
