# Generated by Django 3.0.6 on 2020-05-18 10:22

import accounts.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200518_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='utente',
            field=models.ForeignKey(default=accounts.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
