# Generated by Django 3.0.6 on 2020-05-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200518_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='parola',
            field=models.TextField(),
        ),
    ]
