# Generated by Django 3.0.6 on 2020-05-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200519_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='parola',
            field=models.CharField(max_length=255),
        ),
    ]
